theme: jekyll-theme-minimal
title: VDBX.io
description: <img src="/img/cube-header-web-git.png"/><br> Voidbox Industries designs and creates functional art and electronics widgets. We believe in sharing knowledge so we end up providing our design files and process documentation under an open source license. Many of our products are made from concrete. Follow us on <a href="http://www.instagram.com/vdbxio" target="_blank">Instagram</a> and <a href="http://www.facebook.com/vdbxio" target="_blank">Facebook</a> for the latest updates.
google_analytics: UA-88182510-3
